import { Montserrat, Roboto_Mono } from "next/font/google";
import { headers } from 'next/headers';
import "./globals.css";
import Navbar from "./navbar/page";
import Footer from "./footer/page";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

const robotoMono = Roboto_Mono({
  variable: "--font-roboto-mono",
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function isAuthRoute(pathname) {
  return pathname && (
    pathname.startsWith('/auth') || 
    pathname === '/login' || 
    pathname === '/signup' ||
    pathname === '/reset-password'
  );
}

export default async function RootLayout({ children }) {
  // Get the headers list
  const headersList = await headers();
  // Get the pathname from headers or default to empty string
  const pathname = headersList.get('x-pathname') || '';
  const showLayout = !isAuthRoute(pathname);

  return (
    <html lang="en">
      <body suppressHydrationWarning={true}
        className={`${montserrat.variable} ${robotoMono.variable} antialiased`}
      >
        {showLayout ? (
          <>
            <Navbar />
            <main className="min-h-[calc(100vh-128px)]">
              {children}
            </main>
            <Footer />
          </>
        ) : (
          <div className="min-h-screen bg-gray-50">{children}</div>
        )}
      </body>
    </html>
  );
}
